### PR TITLE
Collision bugfix

### PR DESCRIPTION
**Pull request by JakubJurkovic**
Now it also checks for middle point

### CODE REVIEW

**Comment by NghiaNim** [comment]
Hey, the bat seems to be glitched. Its attack doesn't work and whenever the hero is under it, their attack won't work either. Can you fix that?

**Comment by NghiaNim** [comment]
Hey, I don't wanna make you sad but the bullet still flies through the bat 😥 Can you look through your logic again or maybe another method?

**Comment by JakubJurkovic** [comment]
Found the problem, while I updated my detection logic, I was using yours 😅 I used the collision_rect_right and left, and since I updated the collision_rect the change didn't take a place as it wasn't using the one I worked on. Can you test it now? Also, Jill feels a bit strong, but it might be that I am just too used to these types of characters and never knew how to play tanks.

**Comment by NghiaNim** [comment]
Ah yes, when you're too used to min-maxing that balanced feels weak 😂. Although truth be told, I just think the other guys are a bit too weak lol.

And the changes seem good, I can't seem to miss the bat now 👌

**Pull request merged**
